#!/bin/bash
clear

echo Updating game resources...
./build-preloader-file-list
echo Done.

#echo Compiling CS game logic...
#coffee -b -o core/ coffeecore/
#echo Done.

echo ----------------------------------------------------------------

# python -m SimpleHTTPServer
# Using node's http-server instead. Much faster.
open index.html ; http-server ./ -p 8000