// Generated by CoffeeScript 1.4.0

define(['core/Battle/view/background'], function(addBackground) {
  var clear, draw;
  clear = function() {
    return this.clearRect(0, 0, this.width, this.height);
  };
  draw = function(gfx) {
    if ((gfx != null ? gfx.img : void 0) != null) {
      this.drawImage.apply(this, [gfx.img, gfx.imgdx, gfx.imgdy, gfx.imgw, gfx.imgh, gfx.worldx, gfx.worldy, gfx.imgw, gfx.imgh]);
    }
  };
  return function(world) {
    var backgroundCanvas, canvas, el;
    if (!(world != null)) {
      throw new Error('no world given');
    }
    el = document.createElement('div');
    canvas = document.createElement('canvas');
    backgroundCanvas = addBackground(world);
    el.appendChild(backgroundCanvas);
    el.appendChild(canvas);
    canvas.className = 'noselect';
    canvas.width = world.w;
    canvas.height = world.h;
    el.className = 'battlemap';
    el.style.maxWidth = window.innerWidth;
    el.style.maxHeight = window.innerHeight;
    el.ctx = canvas.getContext('2d');
    el.ctx.width = world.w;
    el.ctx.height = world.h;
    el.ctx.clear = clear;
    el.ctx.draw = draw;
    return el;
  };
});
