
define({
  Decorators: {
    TRUE: true,
    FALSE: false,
    isStoreEmpty: function() {
      return this.store.isEmpty();
    },
    printXY: function() {
      console.log(this.x, this.y);
      return true;
    },
    tryDecayResources: function() {
      this.store.tryDecay();
      return true;
    }
  },
  Trees: {
    Tile: '<[!isStoreEmpty], [printXY], [tryDecayResources]>'
  }
});

// Generated by CoffeeScript 1.5.0-pre
