
define({
  Decorators: {
    TRUE: true,
    FALSE: false,
    storeEmpty: function() {
      return this.store.isEmpty();
    },
    printXY: function() {
      console.log(this.x, this.y);
      return true;
    }
  },
  Trees: {
    Tile: '<[!storeEmpty], [printXY]>'
  }
});

// Generated by CoffeeScript 1.5.0-pre
