// Generated by CoffeeScript 1.6.3
define(function() {
  var sprites, zoom, _;
  sprites = {
    pistol: [8, 8],
    rocket: [8, 8],
    engineer: [8, 8],
    scaffold: [16, 8],
    mine: [5, 2],
    pillbox: [19, 8],
    turret: [22, 9],
    missileracksmall: [4, 7],
    ammodumpsmall: [4, 6],
    missilerack: [5, 9],
    ammodump: [18, 9],
    watchtower: [13, 21],
    relay: [15, 27],
    comm: [28, 28],
    barracks: [32, 12],
    depot: [39, 16],
    helipad: [28, 11],
    repair: [28, 14]
  };
  zoom = function(id, w, h, scale) {
    var c, i, _ref, _ref1;
    if (scale == null) {
      scale = 2;
    }
    id = id.split('/').pop();
    if (!((w != null) && (h != null))) {
      _ref = sprites[id], w = _ref[0], h = _ref[1];
    }
    scale = parseInt(scale);
    c = document.createElement('canvas');
    _ref1 = [scale * w, scale * h], c.width = _ref1[0], c.height = _ref1[1];
    i = new Image;
    i.src = '/images/ingame/' + id + '1.png';
    i.onload = function() {
      var ctx, data, offset, rgba, x, y, _i, _j, _ref2, _ref3;
      ctx = c.getContext('2d');
      ctx.drawImage(i, 0, 0);
      data = ctx.getImageData(0, 0, w, h).data;
      ctx.clearRect(0, 0, c.width, c.height);
      offset = 0;
      for (y = _i = 0, _ref2 = h - 1; 0 <= _ref2 ? _i <= _ref2 : _i >= _ref2; y = 0 <= _ref2 ? ++_i : --_i) {
        for (x = _j = 0, _ref3 = w - 1; 0 <= _ref3 ? _j <= _ref3 : _j >= _ref3; x = 0 <= _ref3 ? ++_j : --_j) {
          rgba = [data[offset++], data[offset++], data[offset++], data[offset++] / 100.0];
          ctx.fillStyle = 'rgba(' + rgba + ')';
          ctx.fillRect(x * scale, y * scale, scale, scale);
        }
      }
    };
    return c;
  };
  _ = window.location.hash.slice(1).split(',');
  if (_.length !== 0) {
    return document.body.appendChild(zoom.apply(void 0, _));
  }
});
