// Generated by CoffeeScript 1.4.0

define(['core/Behaviors', 'core/Battle/addTerrain', 'core/Battle/view/map', 'core/Battle/addUI'], function(Behaviors, Terrain, Map, addUI) {
  var Battle, views, worldBuilders;
  worldBuilders = [Terrain];
  views = {
    Map: Map
  };
  return Battle = (function() {

    function Battle(_) {
      var addTo, world, _i, _len;
      this._ = $.extend({
        w: 3200,
        h: 480
      }, _);
      world = this._;
      for (_i = 0, _len = worldBuilders.length; _i < _len; _i++) {
        addTo = worldBuilders[_i];
        world = addTo(world);
      }
      this._.world = world;
    }

    Battle.prototype.render = function() {
      var k, v;
      this.views = {};
      for (k in views) {
        v = views[k];
        this.views[k] = v(this._.world);
        document.body.appendChild(this.views[k]);
      }
      return this;
    };

    Battle.prototype.cycle = function() {};

    Battle.prototype.addUI = addUI;

    return Battle;

  })();
});
