// Generated by CoffeeScript 1.4.0

define(['core/util/$', 'core/Campaign/addTerrain', 'core/Campaign/addLocations', 'core/Campaign/addTransport', 'core/Campaign/addStorage', 'core/Campaign/addResources', 'core/Campaign/MapView', 'core/campaign/ui'], function($, Terrain, Locations, Transport, Storage, Resources, MapView, UI) {
  var Campaign;
  return Campaign = (function() {

    function Campaign(_) {
      var addTo, world, _i, _len, _ref;
      this._ = $.extend({
        w: 36,
        h: 24
      }, _);
      world = this._;
      _ref = [Terrain, Locations, Transport, Storage, Resources];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        addTo = _ref[_i];
        world = addTo(world);
      }
      this._.world = world;
    }

    Campaign.prototype.render = MapView;

    Campaign.prototype.ui = UI;

    return Campaign;

  })();
});
