// Generated by CoffeeScript 1.4.0

define(['preloader/preloader', 'core/campaign'], function(preloader, Campaign) {
  var c, el, ui;
  window.preloader = preloader;
  c = new Campaign;
  el = c.render();
  ui = c.ui(el);
  return document.body.appendChild(el);
});
