// Generated by CoffeeScript 1.4.0

define(['preloader/preloader', 'core/campaign', 'core/battlec'], function(preloader, Campaign, Battle) {
  var startGame;
  startGame = function() {
    var b, gfxObj;
    b = new Battle().render().addUI();
    gfxObj = {
      img: window.preloader1.getFile('heli0'),
      imgdx: 0,
      imgdy: 0,
      worldx: 0,
      worldy: 0,
      imgw: 100,
      imgh: 100
    };
  };
  window.preloader1 = preloader(startGame);
});
