// Generated by CoffeeScript 1.4.0

define(['preloader/preloader', 'core/campaign', 'core/battlec'], function(preloader, Campaign, Battle) {
  var startGame;
  startGame = function() {
    var b;
    b = new Battle().render().addUI();
  };
  window.preloader1 = preloader(startGame);
});
