// Generated by CoffeeScript 1.4.0

define(['core/util/$', 'core/Resources/Campaign'], function($, Resources) {
  return function(_) {
    var Resources_, giveResources, loc, _i, _len, _ref;
    Resources_ = Resources;
    giveResources = function(loc) {
      var bucket, name, pile, _i, _len;
      pile = {};
      bucket = ($$.shuffle($$.pairs(Resources_))).slice(0, 3);
      for (_i = 0, _len = bucket.length; _i < _len; _i++) {
        name = bucket[_i][0];
        pile[name] = $.R(1, 30);
      }
      return _.map[loc.y][loc.x].store.add(pile);
    };
    _ref = _.locations;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      loc = _ref[_i];
      giveResources(loc);
    }
    return _;
  };
});
