
define(['core/util/$', 'core/Resources/Campaign'], function($, Resources) {
  return function(_) {
    var Resources_, chooseResources, give3RandomResources, giveResources, loc, _i, _len, _ref;
    Resources_ = Resources;
    give3RandomResources = function(loc) {
      var bucket, name, pile, _i, _len;
      pile = {};
      bucket = ($$.shuffle($$.pairs(Resources_))).slice(0, 3);
      for (_i = 0, _len = bucket.length; _i < _len; _i++) {
        name = bucket[_i][0];
        pile[name] = $.R(1, 30);
      }
      return _.map[loc.y][loc.x].store.add(pile);
    };
    chooseResources = function(type) {
      var bucket, bucketObj, bucketSize, item, k, v, _i, _len;
      switch (type) {
        case 'city':
          bucket = [
            {
              'citizen': 2000
            }, {
              'policeman': 5
            }, {
              'food': 2500
            }, {
              'agriculture': 10
            }, {
              'fuel': 250
            }
          ];
          break;
        case 'base':
          bucket = [
            {
              'pistol infantry': 60
            }, {
              'rocket infantry': 20
            }, {
              'engineer infantry': 10
            }, {
              'food': 2000
            }, {
              'alloy': 80
            }, {
              'fuel': 1000
            }, {
              'policeman': 2
            }, {
              'small arms': 30
            }, {
              'small arms ammo': 120
            }, {
              'small rocket launcher': 10
            }, {
              'small rocket': 20
            }, {
              'combustible': 150
            }, {
              'explosive': 50
            }, {
              'munitions factory': 3
            }
          ];
          break;
        case 'farm':
          bucket = [
            {
              'citizen': 100
            }, {
              'policeman': 1
            }, {
              'food': 3000
            }, {
              'agriculture': 1500
            }, {
              'advanced agriculture': 500
            }, {
              'fuel': 750
            }, {
              'metal': 50
            }, {
              'explosive': 10
            }
          ];
          break;
        case 'mine':
          bucket = [
            {
              'citizen': 100
            }, {
              'policeman': 10
            }, {
              'food': 750
            }, {
              'fuel': 750
            }, {
              'metal': 250
            }, {
              'alloy': 10
            }, {
              'combustible': 10
            }, {
              'mining facility': 5
            }, {
              'smelting plant': 2
            }
          ];
          break;
        case 'oilwell':
          bucket = [
            {
              'citizen': 20
            }, {
              'food': 100
            }, {
              'fuel': 400
            }, {
              'metal': 50
            }, {
              'alloy': 10
            }, {
              'oil well': 3
            }, {
              'oil refinery': 2
            }
          ];
          break;
        case 'factory':
          bucket = [
            {
              'citizen': 60
            }, {
              'food': 200
            }, {
              'fuel': 800
            }, {
              'metal': 250
            }, {
              'combustible': 100
            }, {
              'alloy': 100
            }, {
              'munitions factory': 2
            }, {
              'smelting plant': 2
            }, {
              'engineering kit': 10
            }
          ];
      }
      bucketSize = $.R(4, bucket.length);
      bucket = ($$.shuffle(bucket)).slice(0, bucketSize);
      bucketObj = {};
      for (_i = 0, _len = bucket.length; _i < _len; _i++) {
        item = bucket[_i];
        for (k in item) {
          v = item[k];
          bucketObj[k] = $.R(1, v);
        }
      }
      return bucketObj;
    };
    giveResources = function(loc) {
      var pile;
      pile = chooseResources(loc.type);
      return _.map[loc.y][loc.x].store.add(pile);
    };
    _ref = _.locations;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      loc = _ref[_i];
      giveResources(loc);
    }
    return _;
  };
});

// Generated by CoffeeScript 1.5.0-pre
