
define(['core/util/$', 'core/Campaign/Storage'], function($, Storage) {
  return function(_) {
    var settings, tile, tileParams, x, y, _i, _j, _ref, _ref1;
    tileParams = {
      water: {
        size: 0,
        decayRate: 40
      },
      land: {
        size: 1000,
        decayRate: 10
      },
      city: {
        size: 1600,
        decayRate: 2
      },
      base: {
        size: 3000,
        decayRate: 0
      }
    };
    if ((_.h != null) && (_.w != null) && (_.map != null)) {
      for (y = _i = 0, _ref = _.h - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; y = 0 <= _ref ? ++_i : --_i) {
        for (x = _j = 0, _ref1 = _.w - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; x = 0 <= _ref1 ? ++_j : --_j) {
          tile = _.map[y][x];
          if (tile.location != null) {
            settings = tileParams[tile.location.type];
          } else {
            settings = tile.height < _.seaLevel ? tileParams.water : tileParams.land;
          }
          tile.store = new Storage(settings);
        }
      }
      return _;
    }
  };
});

// Generated by CoffeeScript 1.5.0-pre
