
define(['core/util/autoscroll'], function(Autoscroll) {
  return function() {
    var factor, views, _, _ref;
    views = this.views;
    _ = this._;
    factor = 1 / 24;
    if (views != null) {
      if ((_ref = views.Map) != null) {
        _ref.onclick = function(e) {
          var sx, sy, x, y, _ref1, _ref2, _ref3, _ref4, _ref5;
          _ref1 = [views.Map.scrollLeft, views.Map.scrollTop], sx = _ref1[0], sy = _ref1[1];
          _ref2 = [e.pageX + sx, e.pageY + sy], x = _ref2[0], y = _ref2[1];
          _ref3 = [x * factor, y * factor], x = _ref3[0], y = _ref3[1];
          _ref4 = [Math.floor(x), Math.floor(y)], x = _ref4[0], y = _ref4[1];
          if ((_ref5 = views.Inventory) != null) {
            _ref5.show(_.world.map[y][x]);
          }
        };
      }
      Autoscroll(views.Map);
    } else {
      throw new Error('views must be set up prior to adding UI');
    }
    return this;
  };
});

// Generated by CoffeeScript 1.5.0-pre
