// Generated by CoffeeScript 1.4.0

define(['core/util/$', 'core/battle/testSector'], function($, testSector) {
  return function(_) {
    _ = $.extend({
      sectors: testSector,
      sectorWidth: 1024
    }, _);
    if (!(_.w != null) || !(_.h != null)) {
      throw new Error('width or height not set!');
    } else {

    }
    return _;
  };
});
