
define(['core/util/autoscroll'], function(Autoscroll) {
  return function() {
    var views;
    views = this.views;
    if (views != null) {
      Autoscroll(views.Map);
    } else {
      throw new Error('views must be set up prior to adding UI');
    }
    return this;
  };
});

// Generated by CoffeeScript 1.5.0-pre
