
define(['core/util/$'], function($) {
  var i, makeSector, sectors;
  makeSector = function() {
    var sector;
    return sector = {
      height: $.R(1, 15),
      locations: {},
      road: $.R(0, 1) === 1
    };
  };
  return sectors = (function() {
    var _i, _results;
    _results = [];
    for (i = _i = 0; _i <= 4; i = ++_i) {
      _results.push(makeSector);
    }
    return _results;
  })();
});

// Generated by CoffeeScript 1.5.0-pre
