function addExtensionOGG(soundName) { return soundName + '.ogg'; }

// All the sound files to be loaded from assets/sounds/
var list = [
    "acquireload",
    "beep1",
    "chemspray",
    "clicklock",
    "compute",
    "crumble",
    "die1",
    "die2",
    "die3",
    "die4",
    "dropitem",
    "exp2big",
    "expfrag",
    "expsmall",
    "feed",
    "incomingobjective",
    "invalid",
    "jetflyby",
    "load",
    "metalclink",
    "mgburst",
    "missile1",
    "pistol",
    "rocket",
    "sliderack1",
    "tack",
    "turretshot",
    "uv1_acknowledged",
    "uv1_affirmative",
    "uv1_awaitingorders",
    "uv1_notaproblem",
    "uv1_reporting",
    "uv1_rightawaysir",
    "uv1_yessir",
    "uv_turret",
    "v_building",
    "v_cannotbuildhere",
    "v_commandinterfaceinitiated",
    "v_constructioncomplete",
    "v_destroyallenemyforces",
    "v_engineerlost",
    "v_establishanddefendbase",
    "v_insufficientfunds",
    "v_missionaccomplished",
    "v_missionfailed",
    "v_newconstructionoptions",
    "v_newmissionobjective",
    "v_ourbaseisunderattack",
    "v_selectbuildlocation",
    "v_warningincomingenemyforces",
    "v_yourobjective"
];


module.exports = list.map(addExtensionOGG); 
