// Generated by CoffeeScript 1.4.0

define(['core/util/animation'], function(Animation) {
  return function(el) {
    var bShift, margin, origin, radius;
    origin = {
      x: el.offsetTop,
      y: el.offsetLeft,
      w: el.offsetWidth,
      h: el.offsetHeight,
      content: {
        els: el.children,
        el: el.children[0],
        w: el.children[0].scrollWidth,
        h: el.children[0].scrollHeight
      }
    };
    window.foo = origin.content;
    bShift = 3;
    margin = 40;
    radius = {
      x: (el.offsetWidth >> bShift) + margin,
      y: (el.offsetHeight >> bShift) + margin
    };
    el.onmousemove = function(e) {
      var animate, bounds, mx, my, sx, sy, _ref, _ref1;
      _ref = [el.scrollLeft + 0, el.scrollTop + 0], sx = _ref[0], sy = _ref[1];
      _ref1 = [e.pageX - origin.x, e.pageY - origin.y], mx = _ref1[0], my = _ref1[1];
      bounds = {
        left: mx - radius.x,
        right: mx + radius.x,
        top: my - radius.y,
        bottom: my + radius.y
      };
      animate = {};
      if (bounds.left < 0 && sx > 0) {
        animate.scrollLeft = sx + bounds.left;
      } else if (bounds.right > origin.w && sx + origin.w < origin.content.w) {
        animate.scrollLeft = sx + bounds.right - origin.w;
      }
      if (bounds.top < 0 && sy > 0) {
        animate.scrollTop = sy + bounds.top;
      } else if (bounds.bottom > origin.h && sy + origin.h < origin.content.h) {
        animate.scrollTop = sy + bounds.bottom - origin.h;
      }
      if ((animate.scrollTop != null) || (animate.scrollLeft != null)) {
        Animation(el, animate);
      }
    };
    return el;
  };
});
